# Form implementation generated from reading ui file 'gui/dialog_record.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogRecord(object):
    def setupUi(self, DialogRecord):
        DialogRecord.setObjectName("DialogRecord")
        DialogRecord.resize(380, 240)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogRecord)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelDevice = QtWidgets.QLabel(parent=DialogRecord)
        self.labelDevice.setObjectName("labelDevice")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelDevice)
        self.comboDevice = QtWidgets.QComboBox(parent=DialogRecord)
        self.comboDevice.setObjectName("comboDevice")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboDevice)
        self.labelSampleRate = QtWidgets.QLabel(parent=DialogRecord)
        self.labelSampleRate.setObjectName("labelSampleRate")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelSampleRate)
        self.comboSampleRate = QtWidgets.QComboBox(parent=DialogRecord)
        self.comboSampleRate.setObjectName("comboSampleRate")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboSampleRate)
        self.verticalLayout.addLayout(self.formLayout)
        self.vuMeter = QtWidgets.QProgressBar(parent=DialogRecord)
        self.vuMeter.setProperty("value", 0)
        self.vuMeter.setTextVisible(False)
        self.vuMeter.setObjectName("vuMeter")
        self.verticalLayout.addWidget(self.vuMeter)
        self.labelTimer = QtWidgets.QLabel(parent=DialogRecord)
        self.labelTimer.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTimer.setObjectName("labelTimer")
        self.verticalLayout.addWidget(self.labelTimer)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.btnRecord = QtWidgets.QPushButton(parent=DialogRecord)
        self.btnRecord.setObjectName("btnRecord")
        self.buttonLayout.addWidget(self.btnRecord)
        self.btnStop = QtWidgets.QPushButton(parent=DialogRecord)
        self.btnStop.setObjectName("btnStop")
        self.buttonLayout.addWidget(self.btnStop)
        self.btnSave = QtWidgets.QPushButton(parent=DialogRecord)
        self.btnSave.setObjectName("btnSave")
        self.buttonLayout.addWidget(self.btnSave)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(DialogRecord)
        QtCore.QMetaObject.connectSlotsByName(DialogRecord)

    def retranslateUi(self, DialogRecord):
        _translate = QtCore.QCoreApplication.translate
        DialogRecord.setWindowTitle(_translate("DialogRecord", "Gravar Áudio"))
        self.labelDevice.setText(_translate("DialogRecord", "Dispositivo:"))
        self.labelSampleRate.setText(_translate("DialogRecord", "Sample Rate:"))
        self.labelTimer.setText(_translate("DialogRecord", "00:00.00"))
        self.btnRecord.setText(_translate("DialogRecord", "Gravar"))
        self.btnStop.setText(_translate("DialogRecord", "Parar"))
        self.btnSave.setText(_translate("DialogRecord", "Salvar"))
