# Form implementation generated from reading ui file 'gui/effect_widget.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EffectWidget(object):
    def setupUi(self, EffectWidget):
        EffectWidget.setObjectName("EffectWidget")
        EffectWidget.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.horizontalLayout = QtWidgets.QHBoxLayout(EffectWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBypass = QtWidgets.QCheckBox(parent=EffectWidget)
        self.checkBypass.setObjectName("checkBypass")
        self.horizontalLayout.addWidget(self.checkBypass)
        self.labelEffectName = QtWidgets.QLabel(parent=EffectWidget)
        self.labelEffectName.setObjectName("labelEffectName")
        self.horizontalLayout.addWidget(self.labelEffectName)
        self.sliderParam = QtWidgets.QSlider(parent=EffectWidget)
        self.sliderParam.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.sliderParam.setObjectName("sliderParam")
        self.horizontalLayout.addWidget(self.sliderParam)
        self.spinParamValue = QtWidgets.QDoubleSpinBox(parent=EffectWidget)
        self.spinParamValue.setObjectName("spinParamValue")
        self.horizontalLayout.addWidget(self.spinParamValue)

        self.retranslateUi(EffectWidget)

    def retranslateUi(self, EffectWidget):
        _translate = QtCore.QCoreApplication.translate
        self.checkBypass.setText(_translate("EffectWidget", "Bypass"))
        self.labelEffectName.setText(_translate("EffectWidget", "Efeito"))
