# Form implementation generated from reading ui file 'gui/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_status = QtWidgets.QLabel(parent=Dialog)
        self.lbl_status.setObjectName("lbl_status")
        self.verticalLayout.addWidget(self.lbl_status)
        self.btn_load = QtWidgets.QPushButton(parent=Dialog)
        self.btn_load.setObjectName("btn_load")
        self.verticalLayout.addWidget(self.btn_load)
        self.progress_bar = QtWidgets.QProgressBar(parent=Dialog)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout.addWidget(self.progress_bar)
        self.lbl_filepath = QtWidgets.QLabel(parent=Dialog)
        self.lbl_filepath.setObjectName("lbl_filepath")
        self.verticalLayout.addWidget(self.lbl_filepath)
        self.lbl_gate = QtWidgets.QLabel(parent=Dialog)
        self.lbl_gate.setObjectName("lbl_gate")
        self.verticalLayout.addWidget(self.lbl_gate)
        self.lbl_eq = QtWidgets.QLabel(parent=Dialog)
        self.lbl_eq.setObjectName("lbl_eq")
        self.verticalLayout.addWidget(self.lbl_eq)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_status.setText(_translate("Dialog", "Status: Aguardando..."))
        self.btn_load.setText(_translate("Dialog", "Carregar Música de Referência..."))
        self.lbl_filepath.setText(_translate("Dialog", "Nenhum arquivo selecionado."))
        self.lbl_gate.setText(_translate("Dialog", "Threshold do Noise Gate: -- dB"))
        self.lbl_eq.setText(_translate("Dialog", "Curva de EQ Calculada: Bass (--) | Mid (--) | Treble (--)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
