# Form implementation generated from reading ui file 'gui/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(720, 540)
        self.btn_load = QtWidgets.QPushButton(parent=Dialog)
        self.btn_load.setGeometry(QtCore.QRect(10, 10, 212, 26))
        self.btn_load.setObjectName("btn_load")
        self.progress_bar = QtWidgets.QProgressBar(parent=Dialog)
        self.progress_bar.setGeometry(QtCore.QRect(10, 40, 211, 26))
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.lbl_filepath = QtWidgets.QLabel(parent=Dialog)
        self.lbl_filepath.setGeometry(QtCore.QRect(230, 10, 481, 18))
        self.lbl_filepath.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lbl_filepath.setObjectName("lbl_filepath")
        self.lbl_gate = QtWidgets.QLabel(parent=Dialog)
        self.lbl_gate.setGeometry(QtCore.QRect(10, 480, 701, 18))
        self.lbl_gate.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lbl_gate.setObjectName("lbl_gate")
        self.lbl_eq = QtWidgets.QLabel(parent=Dialog)
        self.lbl_eq.setGeometry(QtCore.QRect(10, 510, 701, 18))
        self.lbl_eq.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lbl_eq.setObjectName("lbl_eq")
        self.lbl_status = QtWidgets.QLabel(parent=Dialog)
        self.lbl_status.setGeometry(QtCore.QRect(10, 450, 701, 18))
        self.lbl_status.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lbl_status.setObjectName("lbl_status")
        self.btn_play_orig = QtWidgets.QPushButton(parent=Dialog)
        self.btn_play_orig.setEnabled(False)
        self.btn_play_orig.setGeometry(QtCore.QRect(10, 90, 171, 26))
        self.btn_play_orig.setObjectName("btn_play_orig")
        self.btn_stop_orig = QtWidgets.QPushButton(parent=Dialog)
        self.btn_stop_orig.setEnabled(False)
        self.btn_stop_orig.setGeometry(QtCore.QRect(10, 120, 171, 26))
        self.btn_stop_orig.setObjectName("btn_stop_orig")
        self.btn_stop_guitar = QtWidgets.QPushButton(parent=Dialog)
        self.btn_stop_guitar.setEnabled(False)
        self.btn_stop_guitar.setGeometry(QtCore.QRect(80, 200, 101, 26))
        self.btn_stop_guitar.setObjectName("btn_stop_guitar")
        self.btn_play_guitar = QtWidgets.QPushButton(parent=Dialog)
        self.btn_play_guitar.setEnabled(False)
        self.btn_play_guitar.setGeometry(QtCore.QRect(10, 170, 171, 26))
        self.btn_play_guitar.setObjectName("btn_play_guitar")
        self.lbl_info = QtWidgets.QLabel(parent=Dialog)
        self.lbl_info.setGeometry(QtCore.QRect(230, 40, 481, 20))
        self.lbl_info.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lbl_info.setObjectName("lbl_info")
        self.slider_volume = QtWidgets.QSlider(parent=Dialog)
        self.slider_volume.setGeometry(QtCore.QRect(10, 150, 160, 16))
        self.slider_volume.setMaximum(110)
        self.slider_volume.setProperty("value", 70)
        self.slider_volume.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider_volume.setObjectName("slider_volume")
        self.combo_stems = QtWidgets.QComboBox(parent=Dialog)
        self.combo_stems.setGeometry(QtCore.QRect(10, 200, 71, 26))
        self.combo_stems.setObjectName("combo_stems")
        self.combo_stems.addItem("")
        self.combo_stems.addItem("")
        self.combo_stems.addItem("")
        self.combo_stems.addItem("")
        self.combo_stems.addItem("")
        self.combo_stems.addItem("")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_load.setText(_translate("Dialog", "Carregar Música de Referência..."))
        self.lbl_filepath.setText(_translate("Dialog", "Nenhum arquivo selecionado."))
        self.lbl_gate.setText(_translate("Dialog", "Threshold do Noise Gate: -- dB"))
        self.lbl_eq.setText(_translate("Dialog", "Curva de EQ Calculada: Bass (--) | Mid (--) | Treble (--)"))
        self.lbl_status.setText(_translate("Dialog", "Status: Aguardando..."))
        self.btn_play_orig.setText(_translate("Dialog", "▶ Tocar Original"))
        self.btn_stop_orig.setText(_translate("Dialog", "⏹ Parar"))
        self.btn_stop_guitar.setText(_translate("Dialog", "⏹ Parar"))
        self.btn_play_guitar.setText(_translate("Dialog", "▶ Tocar Faixa Isolada"))
        self.lbl_info.setText(_translate("Dialog", "Música: Nenhuma | Duração: 00:00"))
        self.combo_stems.setItemText(0, _translate("Dialog", "guitar"))
        self.combo_stems.setItemText(1, _translate("Dialog", "bass"))
        self.combo_stems.setItemText(2, _translate("Dialog", "drums"))
        self.combo_stems.setItemText(3, _translate("Dialog", "piano"))
        self.combo_stems.setItemText(4, _translate("Dialog", "vocals"))
        self.combo_stems.setItemText(5, _translate("Dialog", "other"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
