# Form implementation generated from reading ui file 'gui/tab_tonematching.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TabToneMatching(object):
    def setupUi(self, TabToneMatching):
        TabToneMatching.setObjectName("TabToneMatching")
        self.toneMatchingTabLayout = QtWidgets.QVBoxLayout(TabToneMatching)
        self.toneMatchingTabLayout.setContentsMargins(16, 16, 16, 16)
        self.toneMatchingTabLayout.setSpacing(10)
        self.toneMatchingTabLayout.setObjectName("toneMatchingTabLayout")
        self.toneMatchingHeaderLayout = QtWidgets.QHBoxLayout()
        self.toneMatchingHeaderLayout.setObjectName("toneMatchingHeaderLayout")
        self.lbl_tonematching_title = QtWidgets.QLabel(parent=TabToneMatching)
        self.lbl_tonematching_title.setObjectName("lbl_tonematching_title")
        self.toneMatchingHeaderLayout.addWidget(self.lbl_tonematching_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.toneMatchingHeaderLayout.addItem(spacerItem)
        self.btn_run_analysis = QtWidgets.QPushButton(parent=TabToneMatching)
        self.btn_run_analysis.setEnabled(False)
        self.btn_run_analysis.setObjectName("btn_run_analysis")
        self.toneMatchingHeaderLayout.addWidget(self.btn_run_analysis)
        self.toneMatchingTabLayout.addLayout(self.toneMatchingHeaderLayout)
        self.lineSepToneMatchingTop = QtWidgets.QFrame(parent=TabToneMatching)
        self.lineSepToneMatchingTop.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.lineSepToneMatchingTop.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.lineSepToneMatchingTop.setObjectName("lineSepToneMatchingTop")
        self.toneMatchingTabLayout.addWidget(self.lineSepToneMatchingTop)
        self.lbl_analyzed_stem = QtWidgets.QLabel(parent=TabToneMatching)
        self.lbl_analyzed_stem.setText("")
        self.lbl_analyzed_stem.setStyleSheet("color: #888;")
        self.lbl_analyzed_stem.setObjectName("lbl_analyzed_stem")
        self.toneMatchingTabLayout.addWidget(self.lbl_analyzed_stem)
        self.tabsToneMatching = QtWidgets.QTabWidget(parent=TabToneMatching)
        self.tabsToneMatching.setMinimumSize(QtCore.QSize(0, 260))
        self.tabsToneMatching.setObjectName("tabsToneMatching")
        self.tabWaveform = QtWidgets.QWidget()
        self.tabWaveform.setObjectName("tabWaveform")
        self.waveformContainerLayout = QtWidgets.QVBoxLayout(self.tabWaveform)
        self.waveformContainerLayout.setContentsMargins(4, 4, 4, 4)
        self.waveformContainerLayout.setObjectName("waveformContainerLayout")
        self.tabsToneMatching.addTab(self.tabWaveform, "")
        self.tabEqCurve = QtWidgets.QWidget()
        self.tabEqCurve.setObjectName("tabEqCurve")
        self.eqCurveContainerLayout = QtWidgets.QVBoxLayout(self.tabEqCurve)
        self.eqCurveContainerLayout.setContentsMargins(4, 4, 4, 4)
        self.eqCurveContainerLayout.setObjectName("eqCurveContainerLayout")
        self.tabsToneMatching.addTab(self.tabEqCurve, "")
        self.tabSpectralCentroid = QtWidgets.QWidget()
        self.tabSpectralCentroid.setObjectName("tabSpectralCentroid")
        self.spectralCentroidContainerLayout = QtWidgets.QVBoxLayout(self.tabSpectralCentroid)
        self.spectralCentroidContainerLayout.setContentsMargins(4, 4, 4, 4)
        self.spectralCentroidContainerLayout.setObjectName("spectralCentroidContainerLayout")
        self.tabsToneMatching.addTab(self.tabSpectralCentroid, "")
        self.toneMatchingTabLayout.addWidget(self.tabsToneMatching)

        self.retranslateUi(TabToneMatching)
        QtCore.QMetaObject.connectSlotsByName(TabToneMatching)

    def retranslateUi(self, TabToneMatching):
        _translate = QtCore.QCoreApplication.translate
        self.lbl_tonematching_title.setText(_translate("TabToneMatching", "📊  Tone Matching (Librosa)"))
        self.btn_run_analysis.setText(_translate("TabToneMatching", "📊  Executar Tone Matching"))
        self.tabsToneMatching.setTabText(self.tabsToneMatching.indexOf(self.tabWaveform), _translate("TabToneMatching", "🌊  Forma de Onda"))
        self.tabsToneMatching.setTabText(self.tabsToneMatching.indexOf(self.tabEqCurve), _translate("TabToneMatching", "🎚  Curva de EQ"))
        self.tabsToneMatching.setTabText(self.tabsToneMatching.indexOf(self.tabSpectralCentroid), _translate("TabToneMatching", "✨  Brilho (Spectral Centroid)"))
