# Form implementation generated from reading ui file 'gui/tab_hardware.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TabHardware(object):
    def setupUi(self, TabHardware):
        TabHardware.setObjectName("TabHardware")
        self.hardwareTabLayout = QtWidgets.QVBoxLayout(TabHardware)
        self.hardwareTabLayout.setContentsMargins(16, 16, 16, 16)
        self.hardwareTabLayout.setSpacing(12)
        self.hardwareTabLayout.setObjectName("hardwareTabLayout")
        self.lbl_hardware_title = QtWidgets.QLabel(parent=TabHardware)
        self.lbl_hardware_title.setObjectName("lbl_hardware_title")
        self.hardwareTabLayout.addWidget(self.lbl_hardware_title)
        self.lineSepHardwareTop = QtWidgets.QFrame(parent=TabHardware)
        self.lineSepHardwareTop.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.lineSepHardwareTop.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.lineSepHardwareTop.setObjectName("lineSepHardwareTop")
        self.hardwareTabLayout.addWidget(self.lineSepHardwareTop)
        self.btn_send_hardware = QtWidgets.QPushButton(parent=TabHardware)
        self.btn_send_hardware.setEnabled(False)
        self.btn_send_hardware.setObjectName("btn_send_hardware")
        self.hardwareTabLayout.addWidget(self.btn_send_hardware)
        self.lineSepFilters = QtWidgets.QFrame(parent=TabHardware)
        self.lineSepFilters.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.lineSepFilters.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.lineSepFilters.setObjectName("lineSepFilters")
        self.hardwareTabLayout.addWidget(self.lineSepFilters)
        self.filtersHeaderLayout = QtWidgets.QHBoxLayout()
        self.filtersHeaderLayout.setObjectName("filtersHeaderLayout")
        self.lbl_filters_title = QtWidgets.QLabel(parent=TabHardware)
        self.lbl_filters_title.setObjectName("lbl_filters_title")
        self.filtersHeaderLayout.addWidget(self.lbl_filters_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.filtersHeaderLayout.addItem(spacerItem)
        self.btn_query_filters = QtWidgets.QPushButton(parent=TabHardware)
        self.btn_query_filters.setObjectName("btn_query_filters")
        self.filtersHeaderLayout.addWidget(self.btn_query_filters)
        self.hardwareTabLayout.addLayout(self.filtersHeaderLayout)
        self.list_filters = QtWidgets.QListWidget(parent=TabHardware)
        self.list_filters.setMinimumSize(QtCore.QSize(0, 150))
        self.list_filters.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.MultiSelection)
        self.list_filters.setObjectName("list_filters")
        self.hardwareTabLayout.addWidget(self.list_filters)
        self.filtersFooterLayout = QtWidgets.QHBoxLayout()
        self.filtersFooterLayout.setObjectName("filtersFooterLayout")
        self.lbl_filters_status = QtWidgets.QLabel(parent=TabHardware)
        self.lbl_filters_status.setStyleSheet("color: #888;")
        self.lbl_filters_status.setObjectName("lbl_filters_status")
        self.filtersFooterLayout.addWidget(self.lbl_filters_status)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.filtersFooterLayout.addItem(spacerItem1)
        self.btn_apply_filters = QtWidgets.QPushButton(parent=TabHardware)
        self.btn_apply_filters.setEnabled(False)
        self.btn_apply_filters.setObjectName("btn_apply_filters")
        self.filtersFooterLayout.addWidget(self.btn_apply_filters)
        self.hardwareTabLayout.addLayout(self.filtersFooterLayout)

        self.retranslateUi(TabHardware)
        QtCore.QMetaObject.connectSlotsByName(TabHardware)

    def retranslateUi(self, TabHardware):
        _translate = QtCore.QCoreApplication.translate
        self.lbl_hardware_title.setText(_translate("TabHardware", "🔌  Pedal ESP32-S3"))
        self.btn_send_hardware.setText(_translate("TabHardware", "🔌  Enviar Parâmetros de Tone Matching"))
        self.lbl_filters_title.setText(_translate("TabHardware", "🎛  Filtros do Pedal"))
        self.btn_query_filters.setText(_translate("TabHardware", "🔍  Consultar Filtros Disponíveis"))
        self.lbl_filters_status.setText(_translate("TabHardware", "Nenhum filtro consultado ainda."))
        self.btn_apply_filters.setText(_translate("TabHardware", "✅  Aplicar Filtros Selecionados"))
