# Form implementation generated from reading ui file 'gui/tab_hardware.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TabHardware(object):
    def setupUi(self, TabHardware):
        TabHardware.setObjectName("TabHardware")
        self.hardwareTabLayout = QtWidgets.QVBoxLayout(TabHardware)
        self.hardwareTabLayout.setContentsMargins(16, 16, 16, 16)
        self.hardwareTabLayout.setSpacing(10)
        self.hardwareTabLayout.setObjectName("hardwareTabLayout")
        self.lbl_hardware_title = QtWidgets.QLabel(parent=TabHardware)
        self.lbl_hardware_title.setObjectName("lbl_hardware_title")
        self.hardwareTabLayout.addWidget(self.lbl_hardware_title)
        self.lineSepHardwareTop = QtWidgets.QFrame(parent=TabHardware)
        self.lineSepHardwareTop.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.lineSepHardwareTop.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.lineSepHardwareTop.setObjectName("lineSepHardwareTop")
        self.hardwareTabLayout.addWidget(self.lineSepHardwareTop)
        self.lbl_hardware_hint = QtWidgets.QLabel(parent=TabHardware)
        self.lbl_hardware_hint.setWordWrap(True)
        self.lbl_hardware_hint.setStyleSheet("color: #888; font-size: 11px;")
        self.lbl_hardware_hint.setObjectName("lbl_hardware_hint")
        self.hardwareTabLayout.addWidget(self.lbl_hardware_hint)
        self.lbl_gate_source = QtWidgets.QLabel(parent=TabHardware)
        self.lbl_gate_source.setText("")
        self.lbl_gate_source.setStyleSheet("color: #888; font-size: 11px;")
        self.lbl_gate_source.setObjectName("lbl_gate_source")
        self.hardwareTabLayout.addWidget(self.lbl_gate_source)
        self.containerEffects = QtWidgets.QWidget(parent=TabHardware)
        self.containerEffects.setObjectName("containerEffects")
        self.effectsContainerLayout = QtWidgets.QVBoxLayout(self.containerEffects)
        self.effectsContainerLayout.setContentsMargins(0, 0, 0, 0)
        self.effectsContainerLayout.setSpacing(10)
        self.effectsContainerLayout.setObjectName("effectsContainerLayout")
        self.hardwareTabLayout.addWidget(self.containerEffects)
        self.lineSepHardwareBottom = QtWidgets.QFrame(parent=TabHardware)
        self.lineSepHardwareBottom.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.lineSepHardwareBottom.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.lineSepHardwareBottom.setObjectName("lineSepHardwareBottom")
        self.hardwareTabLayout.addWidget(self.lineSepHardwareBottom)
        self.btn_send_hardware = QtWidgets.QPushButton(parent=TabHardware)
        self.btn_send_hardware.setObjectName("btn_send_hardware")
        self.hardwareTabLayout.addWidget(self.btn_send_hardware)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.hardwareTabLayout.addItem(spacerItem)

        self.retranslateUi(TabHardware)
        QtCore.QMetaObject.connectSlotsByName(TabHardware)

    def retranslateUi(self, TabHardware):
        _translate = QtCore.QCoreApplication.translate
        self.lbl_hardware_title.setText(_translate("TabHardware", "🔌  Pedal ESP32-S3"))
        self.lbl_hardware_hint.setText(_translate("TabHardware", "Os controles abaixo espelham os efeitos disponíveis no firmware. O Noise Gate pode ser preenchido automaticamente a partir do Tone Matching, ou ajustado manualmente aqui."))
        self.btn_send_hardware.setText(_translate("TabHardware", "🔌  Enviar Estado para o Pedal"))
